GET http://localhost:3000/films
###

GET http://localhost:3000/films/1
###

POST http://localhost:3000/addFilm
Content-Type: application/json

{
    "title": "New Film Title",
    "isFavorite": true,
    "watchDate": "2024-03-25",
    "rating": 4
}
###

PATCH http://localhost:3000/updateFav/5/favorite
Content-Type: application/json

{
    "isFavorite": true
}
###

PATCH http://localhost:3000/updateRating/1/rating
Content-Type: application/json

{
    "rating": 5
}
###

DELETE http://localhost:3000/deleteFilm/7
###

GET http://localhost:3000/filteredFilms
###

GET http://localhost:3000/filteredFilms?filter=favorite
###

GET http://localhost:3000/filteredFilms?filter=best
###

GET http://localhost:3000/filteredFilms?filter=lastmonth
###

GET http://localhost:3000/filteredFilms?filter=unseen
###

PUT http://localhost:3000/updateFilm/7
Content-Type: application/json

{
    "title": "Updated Title",
    "isFavorite": true,
    "watchDate": "2024-03-15",
    "rating": 4.5
}